### ISSUE TITLE
기본 기능 개발

### ISSUE THREAD

**Issue by Neptunerere** [Team-GGL/ggl-aris-bot#1]
# Description
> 디스코드 봇이 기본적인 동작을 하기 위한 기능 개발

# To-do

- [x] 기본 메시지 생성
- [ ] 환영인사 생성
- [ ] 도움말 생성
- [x] 상태 메시지 랜덤 생성
- [ ] 유저 정보 생성
- [x] 할까말까 생성
- [ ] 음식 추천 생성
- [ ] 게임 추천 생성
